name: Pipeline de Testes Automatizados da API

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v4

      - name: Configurar Node.js (versão 20)
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências do projeto
        run: npm ci

      - name: Criar arquivo .env
        env:
          ENV_CONTENT: ${{ secrets.TEST_SECRETS }}
        run: |
          echo "$ENV_CONTENT" > .env

      - name: Iniciar API
        run: nohup npm start > server.log 2>&1 &

      - name: Aguardar API
        run: curl --retry 30 --retry-all-errors --retry-delay 1 --fail http://localhost:3000/

      - name: Executar testes
        run: npm test

      - name: Exibir logs da API se houver falha
        if: failure()
        run: cat server.log